### ISSUE TITLE
Jakieś plany? np uml-e

### ISSUE THREAD

**Issue by slawomirsk** [wojciechzurek/InteligentnyDomek#1]
https://pl.wikipedia.org/wiki/Unified_Modeling_Language

**Comment by wojciechzurek** [comment]
Do czego to? Bo nie za bardzo rozumiem.

**Comment by slawomirsk** [comment]
Jest to język modelowania ( nie programowania) systemów. Składa się on z kilkunastu rodzajów diagramów które mogą opisywać np dziedziczenie w klasach, zachowanie się systemu w trakcie wykonywania jakiegoś zadania, interakcję systemu i użytkownika-user case.

**Comment by joniomateusz** [comment]
![main](https://cloud.githubusercontent.com/assets/26435761/25202201/cae760f8-2554-11e7-83c0-670275736f89.jpg)
